// ClipboardPrivacy.swift
// Quick — 原生 macOS 效率启动器
// @author ygw

import Foundation

/// 剪贴板隐私过滤
///
/// 密码管理器与部分应用会在 NSPasteboard 上挂约定类型，声明「这段内容不要进历史」。
/// 见 <https://nspasteboard.org>。
enum ClipboardPrivacy {

    /// 任一存在即跳过入库
    static let skipTypeIdentifiers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// 当前剪贴板类型列表是否应跳过记录
    static func shouldSkip(typeIdentifiers: [String]) -> Bool {
        typeIdentifiers.contains { skipTypeIdentifiers.contains($0) }
    }
}
