// ClipboardPrivacyTests.swift
// Quick — 原生 macOS 效率启动器
// @author ygw

import Testing

@testable import PluginClipboard

@Suite("剪贴板隐私过滤")
struct ClipboardPrivacyTests {

    @Test("普通文本类型不跳过")
    func allowsOrdinaryTypes() {
        #expect(!ClipboardPrivacy.shouldSkip(typeIdentifiers: ["public.utf8-plain-text"]))
        #expect(!ClipboardPrivacy.shouldSkip(typeIdentifiers: ["public.tiff", "public.png"]))
        #expect(!ClipboardPrivacy.shouldSkip(typeIdentifiers: []))
    }

    @Test("Concealed / Transient / AutoGenerated 任一存在即跳过")
    func skipsDeclaredHiddenTypes() {
        #expect(
            ClipboardPrivacy.shouldSkip(typeIdentifiers: [
                "public.utf8-plain-text",
                "org.nspasteboard.ConcealedType",
            ]))
        #expect(
            ClipboardPrivacy.shouldSkip(typeIdentifiers: [
                "org.nspasteboard.TransientType"
            ]))
        #expect(
            ClipboardPrivacy.shouldSkip(typeIdentifiers: [
                "org.nspasteboard.AutoGeneratedType",
                "public.png",
            ]))
    }
}
